/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itee_exam_tools_PayTools */

#ifndef _Included_com_itee_exam_tools_PayTools
#define _Included_com_itee_exam_tools_PayTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itee_exam_tools_PayTools
 * Method:    getAlipayParam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itee_exam_tools_PayTools_getAlipayParam(JNIEnv *, jobject obj,jobject pay);

JNIEXPORT jstring JNICALL Java_com_itee_exam_tools_PayTools_getWeixinParam(JNIEnv *, jobject obj,jobject pay);
#ifdef __cplusplus
}
#endif
#endif
